CREATE TABLE PAGES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   PAGE_NUM INTEGER NOT NULL,
   ATTRIBUT TEXT,
   CONTENT TEXT
);

INSERT INTO PAGES (PAGE_NUM,ATTRIBUT, CONTENT)
VALUES (1, 'text',"Voilà la première page du livre");
INSERT INTO PAGES (PAGE_NUM,ATTRIBUT, CONTENT)
VALUES (2, 'text',"Voilà la deuxième page du livre");
INSERT INTO PAGES (PAGE_NUM,ATTRIBUT, CONTENT)
VALUES (3, 'text',"Voilà la troisième page du livre");
INSERT INTO PAGES (PAGE_NUM,ATTRIBUT, CONTENT)
VALUES (4, 'text',"Voilà la quatrième page du livre");



